import { StyleSheet } from "react-native";

export const SignStyles = StyleSheet.create({
    SignCon:{
        flex:1,
        display:'flex',
        flexDirection:'column',
        alignItems:'center',
        justifyContent:'center',
        width:'100%',
        padding:20
    },
    SignHead:{
        fontSize:24,
        fontWeight:700,
        color:'black',
        textAlign:'center',
        textTransform:'capitalize'
    },
    SignHeadTag:{
        fontSize:12,
        color:'grey',
        fontWeight:500,
        textAlign:'center',
        textTransform:'capitalize',
        marginTop:5,
        marginBottom:40
    },
    SignLabelCon:{
        width:'100%',
        marginTop:10,
        display:'flex',
        flexDirection:'column',
        gap:5
    },
    SignLabel:{
        fontSize:14,
        color:'black',
        fontWeight:500
    },
    SignInput:{
        backgroundColor:'#F6F6F6',
        borderRadius:10,
        paddingLeft:10
    },
    SignBtn:{
        height:45,
        padding:5,
        borderRadius:5,
        display:'flex',
        flexDirection:'column',
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:'#2853AF',
        width:'100%',
        marginTop:20,
        borderRadius:10
    },
    SignBtnText:{
        color:'white',
        fontSize:14,
        textTransform:'capitalize',
        fontWeight:500,
        textAlign:'center'
    },
    SignBtnBelowTag:{
        fontWeight:600,
        textAlign:'center',
        marginTop:10,
        color:'#78828A'
    }
});