import { StyleSheet } from "react-native";

export const OnboardStyles = StyleSheet.create({
    container:{
        flex:1,
        display:'flex',
        flexDirection:'column',
        alignItems:'center',
        justifyContent:'flex-end',
        padding:10,
        width:'100%'
    },
    innerContainer:{
        display:'flex',
        flexDirection:'column',
        gap:5,
        width:'100%'
    },
    headerText:{
        fontSize:24,
        fontWeight:700,
        color:'white',
        textAlign:'center',
        textTransform:'capitalize',
    },
    headerTag:{
        fontSize:14,
        color:'#E3E9ED',
        fontWeight:400,
        textAlign:'center',
        marginTop:5,
        marginBottom:5
    },
    OnboardingBtnsCon:{
        display:'flex',
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'center',
        gap:5
    },
    activeBtn:{
        width:25,
        borderRadius:20,
        backgroundColor:'#2853AF'
    },
    OnboardingBtns:{
        width:10,
        height:10,
        borderRadius:'50%',
        backgroundColor:'#BFC6CC'
    },
    ContinueBtn:{
        width:'90%',
        height:45,
        backgroundColor:'#2853AF',
        display:'flex',
        flexDirection:'column',
        alignItems:'center',
        justifyContent:'center',
        padding:5,
        borderRadius:10,
        margin:'auto',
        marginTop:15,
        marginBottom:15
    },
    ContinueText:{
        color:'white',
        fontSize:14,
        fontWeight:500,
        textTransform:'capitalize'
    }
});