import { StyleSheet } from "react-native";

export const ProfileStyles = StyleSheet.create({
    profileCon:{
        flex:1,
        backgroundColor:'white',
        padding:10
    },
    profileHead:{
        textAlign:'center',
        fontSize:16,
        fontWeight:500,
        marginTop:5,
        marginBottom:5
    },

    personData:{
        display:'flex',
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        marginTop:10,
        marginBottom:10
    },
    personInner:{
        display:'flex',
        flexDirection:'row',
        alignItems:'center',
        gap:10
    },
    personName:{
        fontSize:14,
        fontWeight:500,
        color:'black',
        textTransform:'capitalize'
    },
    personEmail:{
        fontSize:12,
        color:'grey'
    },
    //settings
    settingsHead:{
        fontSize:14,
        fontWeight:500,
        color:'grey',
        textTransform:'capitalize',
        marginTop:15,
        marginBottom:10
    },
    settingsEachCon:{
        display:'flex',
        flexDirection:'row',
        alignItems:'center',
        gap:10,
        padding:10
    },
    settingsEachText:{
        fontWeight:500,
        color:'black',
        fontSize:14,
        textTransform:'capitalize'
    },
    settingsBreakLine:{
        width:'80%',
        height:0.5,
        backgroundColor:'#E9EBED',
        margin:'auto',
        marginTop:4,
        marginBottom:5
    },
    logout:{
        fontWeight:500,
        color:'red',
        fontSize:14,
        textAlign:'center',
        textTransform:'capitalize',
        marginTop:20
    }

});