import { StyleSheet } from "react-native";

export const HomeStyles = StyleSheet.create({
    //profile con
    profileCon:{
        display:'flex',
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        padding:15
    },
    profileNameCon:{
        display:'flex',
        flexDirection:'row',
        alignItems:'center',
        gap:10
    },
    profileNotify:{
        padding:10,
        borderWidth:1,
        borderRadius:'50%',
        borderColor:'black'
    },
    //home styles header view
    HomeTopicHeader:{
        display:'flex',
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        padding:15
    },
    HomeTopicTextOne:{
        fontSize:14,
        fontWeight:700,
        color:'black',
        textTransform:'capitalize'
    },
    HomeTopicTextTwo:{
        fontSize:14,
        color:'#2853AF',
        textTransform:'capitalize'
    },
    popularEach:{
        width:140,
        height:190,
        resizeMode:'cover',
        borderRadius:10,
        overflow:'hidden',
        marginRight:10
    },
    popularEachInner:{
        width:'100%',
        // flex:1,
        height:'100%',
        backgroundColor:'rgba(0,0,0,0.3)',
        display:'flex',
        flexDirection:'column',
        justifyContent:'flex-end',
        padding:5,
        position:'relative'
    },
    popularHtlName:{
        fontSize:13,
        fontWeight:700,
        color:'white',
        textTransform:'capitalize'
    },
    popularHtlTag:{
        fontSize:10,
        color:'white',
        fontWeight:500
    },
    popularpriceCon:{
        display:'flex',
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        marginTop:5
    },
    popularpriceText:{
        fontSize:11,
        color:'white',
        fontWeight:500
    },
    popularWishlist:{
        position:'absolute',
        top:10,
        right:10
    },
    //recommended hotels
    recomHtlName:{
        paddingHorizontal:15,
        paddingVertical:4,
        height:30,
        display:'flex',
        flexDirection:'column',
        alignItems:'center',
        justifyContent:'center',
        // backgroundColor:'#2853AF',
        backgroundColor:'white',
        borderWidth:1,
        borderRadius:5,
        borderColor:'#E9EBED'
    },
    recomhtltext:{
        color:'#78828A',
        fontSize:14,
        fontWeight:400,
        textTransform:'capitalize'
    },
    activeRecomhtltext:{
        color:'white',
        backgroundColor:'#2853AF'
    },
    recomEachCon:{
        width:'95%',
        backgroundColor:'white',
        minHeight:70,
        margin:'auto',
        marginTop:5,
        marginBottom:5,
        paddingHorizontal:10,
        paddingVertical:10,
        borderRadius:5,
        display:'flex',
        flexDirection:'row',
        justifyContent:'space-between',
        gap:5,
        borderBottomWidth:1,
        borderBottomColor:'#E9EBED'
    },
    recomImgName:{
        display:'flex',
        flexDirection:'row',
        gap:5
    },
    bestTopCon:{
        width:'90%',
        margin:'auto',
        marginTop:10,
        minHeight:100,
        backgroundColor:'white',
        padding:10,
        borderWidth:1,
        borderColor:'#E9EBED',
        borderRadius:10,
        marginBottom:3
    },
    bestHotelNameCon:{
        display:'flex',
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        marginTop:10
    },

    bedsText:{
        fontSize:10,
        fontWeight:400,
        marginTop:4,
        marginLeft:2
    }


});